name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-static-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Show Deployment Environment
        run: echo "Deploying to environment: ${{ secrets.DEPLOY_ENV }}"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

